function festwert_spec

K_SOME_SCALAR = 1.50;
K_SOME_TEXT = {'foo'};

% Save labels to a temporary file
save('tmp.mat', '-regexp', '^K_SOME_');

% Export using mat2dcm
mat2dcm('tmp.mat', 'tmp.dcm', ...
  'Precision', '%1.3f', ...
  'Prefix', '', ...
  'Verbose', false);
filecontent = regexprep(fileread('tmp.dcm'), '\r', '');

% FESTWERT numeric
expect(~isempty(regexp(filecontent, [...
  'FESTWERT K_SOME_SCALAR\n' ...
  '   WERT 1.500\n' ...
  'END\n' ...
])));

% FESTWERT text
expect(~isempty(regexp(filecontent, [...
  'FESTWERT K_SOME_TEXT\n' ...
  '   TEXT "foo"\n' ...
  'END\n' ...
])));
