function function_spec

K_SOME_SCALAR = 1.50;

% Save labels to a temporary file
save('tmp.mat', '-regexp', '^K_SOME_');

% Export using mat2dcm
mat2dcm('tmp.mat', 'tmp.dcm', ...
  'Precision', '%1.3f', ...
  'Prefix', '', ...
  'Function', 'SOME_FUNCTION', ...
  'Verbose', false);
filecontent = regexprep(fileread('tmp.dcm'), '\r', '');

% FESTWERT numeric
expect(~isempty(regexp(filecontent, [...
  'FESTWERT K_SOME_SCALAR\n' ...
  '   FUNKTION SOME_FUNCTION\n' ...
  '   WERT 1.500\n' ...
  'END\n' ...
])));
