function kennlinie_spec

KL_SOME_LOOKUP_LINE.x = [-10 0   100];
KL_SOME_LOOKUP_LINE.y = [2  -0.1 2.1];

% Save labels to a temporary file
save('tmp.mat', '-regexp', '^KL_SOME_');

% Export using convert_to_dcm
convert_to_dcm('tmp.mat', 'tmp.dcm', ...
  'Precision', '%1.3f', ...
  'Prefix', '', ...
  'Verbose', false);
filecontent = regexprep(fileread('tmp.dcm'), '\r', '');

% KENNLINIE numeric/numeric
myassert(~isempty(regexp(filecontent, [...
'KENNLINIE KL_SOME_LOOKUP_LINE 3\n' ...
'   ST/X   -10.000   0.000   100.000\n' ...
'   WERT   2.000   -0.100   2.100\n' ...
'END\n' ...
])));
