function prefix_spec

K_SOME_SCALAR = 1.50;

% Save labels to a temporary file
save('tmp.mat', '-regexp', '^K_SOME_');

% Export using mat2dcm
mat2dcm('tmp.mat', 'tmp.dcm', ...
  'Precision', '%1.3f', ...
  'Prefix', 'Foo_bar.', ...
  'Verbose', false);
filecontent = regexprep(fileread('tmp.dcm'), '\r', '');

% FESTWERT numeric
myassert(~isempty(regexp(filecontent, [...
  'FESTWERT Foo_bar.K_SOME_SCALAR\n' ...
  '   WERT 1.500\n' ...
  'END\n' ...
])));
